spring.application.name=C2C

#server port
server.port=9999

#oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=your_oracle_jdbc_url
spring.datasource.username=your_oracle_username
spring.datasource.password=your_oracle_password

#mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
mybatis.configuration.jdbc-type-for-null=NULL

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_mail_username
spring.mail.password=your_mail_app_password
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#jwt -> expire-hour : token to endtime set
jwt.secret-key=your_jwt_secret_key
jwt.expire-hour=1

#file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-part-count=50

#file upload location
file.root=your_file_upload_root
